name: first workflows
on: workflows_dispatch
jobs: 
   first-job:
     runs-on: ubuntu-latest
     steps:
       - name: print greeting
         run: echo "hello world"
       - name: print goodbye
         run: echo "print goodbye"
