name: Java CI with maven

on:
  push:
  branches: [ anshit ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
        
        - name: Build and push Docker images
          uses: docker/build-push-action@v4.0.0
          with :
           image: anshit84/neosoft
           registry: docker.io
           username: anshit84
           password: anshit@123
           


 
      
