name: workflow1
on:  [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
       - name: getcode
         uses: actions/checkout@v2

       - name: set up jdk17
         uses: actions/setup-java@v1.4.4
         with:
           java-version: 17
       - name: Build with Maven
         run:  mvn -B package --file pom.xml
       - name: test with maven
         run: mvn test --file pom.xml
  Build:
    needs: test
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2

        - name: set up jdk17
          uses: actions/setup-java@v1.4.4
          with:
            java-version: 17
        - name: Build with Maven
          run: mvn -B package --file pom.xml
        - name: build with maven
          uses: actions/upload-artifact@v3
          with:
            path: target
  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
        - name: get build artifact
          uses: actions/download-artifact@v3
          with:
            name: target-files
        - name: output contents
          runs: ls
        - name: deploy
          run: echo "deploying..!"



